### ISSUE TITLE
Homework

### ISSUE THREAD

**Issue by Taiga74164** [GrownNed/Homework#1]
I need help with Calculus homework 🥺

**Comment by GrownNed** [comment]
![20220913_160732](https://user-images.githubusercontent.com/46023721/190051066-af25d5dd-1123-4b6a-8297-1c0714d7d73b.jpg)
I can help you with geometry

**Comment by Taiga74164** [comment]
Thank you mero. I just printed this right now. I will submit it tomorrow 😌

**Comment by GrownNed** [comment]
Waiting for results
